services:
  - type: web
    name: adhaar-ocr
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    runtime: python
